
name: CI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }} 
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
            git pull origin main
            composer install
            npm install
            npm run build